# action.yml
name: 'Sql Syntax check'
description: 'Check syntax for your sql files'
inputs:
  fileInput:  
    description: 'File to check'
    required: true
outputs:
  result: 
    description: 'Syntax check result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ fileInput }}
