# action.yml
name: 'Sql Syntax check'
description: 'Check syntax for your sql files'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  result: 
    description: 'Syntax check result'
runs:
  using: 'docker'
  image: 'sql-syntax-action/Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}    