on:
  push:
    paths:
    - '**.sql'
    
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Sql Syntax check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: print files with .sql extension
        run : |
           STEP_FILES=$(find . -name '*.sql')
           echo ---
           echo $STEP_FILES
           echo ---
      - name: Hello world action step
        uses:  # Uses an action in the root directory
        id: hello
        with:
          fileInput: $STEP_FILES
